const fs = require("fs");
const path = require("path");

// Load the JSON data
const jsonData = {
  10: "10",
  11: "11",
  12: "12",
  15: "15",
  22: "22",
  29: "29",
  39: "39",
  69: "69",
  75: "75",
  89: "89",
  120: "120",
  150: "150",
  189: "189",
  229: "229",
  790: "790",
  939: "939",
  2021: "2021",
  2022: "2022",
  2023: "2023",
  2024: "2024",
  2025: "2025",
  2026: "2026",
  2027: "2027",
  2028: "2028",
  2029: "2029",
  2030: "2030",
  2031: "2031",
  $0: "$0",
  "+8%": "8%",
  "-27%": "-27٪",
  "+28%": "28%",
  "-34%": "-34٪",
  "+42": "42",
  "47%": "47%",
  "+48%": "48%",
  $49: "49 دلار",
  "50+": "50",
  "+52%": "52%",
  "(59)": "(59)",
  "60%": "60%",
  "65%": "65%",
  "70%": "70%",
  "71%": "71%",
  "72%": "72%",
  "80%": "80%",
  "+82$": "82 دلار",
  "83%": "83%",
  "90%": "90%",
  "+105$": "105 دلار",
  "+230%": "230%",
  $240: "240 دلار",
  "+280$": "280 دلار",
  $520: "520 دلار",
  $593: "593 دلار",
  $650: "650 دلار",
  $706: "706 دلار",
  $750: "750 دلار",
  $980: "980 دلار",
  $3560: "3560 دلار",
  "4500$": "4500 دلار",
  $4850: "4850 دلار",
  $8376: "8376 دلار",
  $8476: "8476 دلار",
  $9486: "9486 دلار",
  "#45890": "",
  "#67890": "",
  "Layout Builder": "Layout Builder",
  Crafted: "ساخته شده است",
  Pages: "صفحات",
  Profile: "مشخصات",
  Overview: "بررسی اجمالی",
  Projects: "پروژه ها",
  Campaigns: "کمپین ها",
  Documents: "اسناد",
  Connections: "اتصالات",
  Wizards: "جادوگران",
  Horizontal: "افقی",
  Vertical: "عمودی",
  Accounts: "حساب ها",
  Settings: "تنظیمات",
  Errors: "خطاها",
  "Error 404": "خطای 404",
  "Error 500": "خطای 500",
  Widgets: "ابزارک ها",
  Lists: "لیست ها",
  Statistics: "آمار",
  Charts: "نمودار",
  Mixed: "مختلط",
  Tables: "جداول",
  Feeds: "تغذیه می کند",
  Apps: "برنامه ها",
  Chat: "چت کنید",
  "Private Chat": "گفتگوی خصوصی",
  "Group Chat": "چت گروهی",
  DRAWER_CHAT: "DRAWER_CHAT",
  "Docs & Components": "اسناد",
  Keenthemes: "Keenthemes",
  About: "درباره",
  Support: "حمایت کردن",
  Purchase: "خرید",
  "Light Header": "سربرگ نور",
  "Customize view": "نمایش را سفارشی کنید",
  Actions: "اقدامات",
  Progress: "پیش رفتن",
  "Today 16 Feb": "امروز 16 بهمن",
  "In Progress": "در حال پیش رفت",
  Done: "انجام شده",
  Filters: "فیلترها",
  Filter: "فیلتر کنید",
  "Loading date range...": "در حال بارگیری محدوده تاریخ...",
  Create: "ايجاد كردن",
  Team: "تیم",
  A: "آ",
  S: "اس",
  P: "پ",
  "Sort By:": "مرتب سازی بر اساس:",
  Latest: "آخرین",
  "Filter By:": "محدود شده توسط:",
  Today: "امروز",
  Week: "هفته",
  Day: "روز",
  "Impact Level:": "سطح تاثیر:",
  "Quick Tools:": "ابزارهای سریع:",
  "Avg. Earnings": "میانگین ",
  "Total Sales": "کل فروش",
  "Send Message": "پیام فرستادن",
  "Due Date": "سررسید",
  Budget: "بودجه",
  Connect: "اتصال",
  You: "شما",
  Send: "ارسال",
  "Filter Options": "گزینه های فیلتر",
  Status: "وضعیت",
  Approved: "تایید شده",
  Pending: "انتظار",
  "In Process": "در جریان",
  Rejected: "رد شد",
  "Member Type:": "نوع عضو:",
  Author: "نویسنده",
  Customer: "مشتری",
  Notifications: "اطلاعیه",
  Enabled: "فعال شد",
  Reset: "بازنشانی کنید",
  Apply: "درخواست دادن",
  "Quick Actions": "اقدامات سریع",
  "New Ticket": "بلیط جدید",
  "New Customer": "مشتری جدید",
  "New Group": "گروه جدید",
  "Admin Group": "گروه مدیریت",
  "Staff Group": "گروه کارکنان",
  "Member Group": "گروه اعضا",
  "New Contact": "تماس جدید",
  "Generate Reports": "ایجاد گزارش",
  Payments: "مبلغ پرداختی",
  "Create Invoice": "ایجاد فاکتور",
  "Create Payment": "ایجاد پرداخت",
  "Generate Bill": "بیل را ایجاد کنید",
  Subscription: "اشتراک، ابونمان",
  Plans: "طرح ها",
  Billing: "صورتحساب",
  Statements: "بیانیه",
  Recuring: "عود کننده",
  "69,700": "69700",
  "2.2%": "2.2٪",
  "Projects Earnings in April": "درآمد پروژه ها در ماه آوریل",
  "Leaf CRM": "CRM برگ",
  "$7,660": "7660 دلار",
  "اپ‌های کوچک": "اپهای کوچک",
  "$2,820": "2820 دلار",
  Others: "دیگران",
  "$45,257": "45257 دلار",
  Featured: "ویژه",
  "9 Degree": "9 درجه",
  Manager: "مدیر",
  "Robert Fox": "رابرت فاکس",
  "$64.800": "64.800 دلار",
  "Flat cartoony illustrations with vivid": "تصاویر کارتونی تخت با واضح",
  "unblended colors and asymmetrical beautiful purple hair lady":
    "رنگ های نامتقارن و موهای زیبای بنفش نامتقارن خانم",
  "Feb 6, 2021": "6 فوریه 2021",
  "View Project": "مشاهده پروژه",
  "43 Pending": "43 در انتظار",
  "Today’s Heroes": "قهرمانان امروز",
  "Performance Overview": "بررسی اجمالی عملکرد",
  "Users from all channels": "کاربران از همه کانال ها",
  Month: "ماه",
  "18,89": "18,89",
  "4,8%": "4.8٪",
  "Avarage cost per interaction": "هزینه متوسط ​​در هر تعامل",
  "Social Campaigns": "کمپین های اجتماعی",
  "Google Ads": "تبلیغات گوگل",
  "Email Newsletter": "خبرنامه ایمیل",
  Courses: "دوره های آموزشی",
  "TV Campaign": "کمپین تلویزیونی",
  Radio: "رادیو",
  "8,55": "8,55",
  "Try our all new Enviroment with": "تمام محیط جدید ما را با آن امتحان کنید",
  "Pro Plan": "طرح حرفه ای",
  "for Free": "رایگان",
  "Upgrade Now": "اکنون ارتقا دهید",
  "External Links": "لینک های خارجی",
  "tables-widget16 works!": "tables-widget16 کار می کند!",
  "Agents Stats": "آمار نمایندگان",
  "More than 400 new members": "بیش از 400 عضو جدید",
  "Add New Member": "اضافه کردن عضو جدید",
  Authors: "نویسندگان",
  Company: "شرکت",
  action: "عمل",
  "Brad Simmons": "برد سیمونز",
  "HTML, JS, ReactJS": "HTML، JS، ReactJS",
  Intertico: "اینترتیکو",
  "Web, UI/UX Design": "طراحی وب، UI/UX",
  "Jessie Clarcson": "جسی کلارکسون",
  "C#, ASP.NET, MS SQL": "سی",
  Agoda: "آگودا",
  "Houses & Hotels": "خانه ها",
  "Lebron Wayde": "لبرون وید",
  "PHP, Laravel, VueJS": "PHP، Laravel، VueJS",
  RoadGee: "RoadGee",
  Transportation: "حمل و نقل",
  "Natali Trump": "ناتالی ترامپ",
  "Python, PostgreSQL, ReactJS": "Python، PostgreSQL، ReactJS",
  "The Hill": "تپه",
  Insurance: "بیمه",
  "New Arrivals": "تازه رسیده ها",
  "Sant Outstanding": "سنت برجسته",
  Email: "پست الکترونیک",
  "bprow@bnc.cc": "bprow@bnc.cc",
  "$2,000,000": "2,000,000 دلار",
  Paid: "پرداخت شده",
  "ReactJs, HTML": "ReactJs، HTML",
  "Application Development": "توسعه برنامه",
  "app@dev.com": "app@dev.com",
  "$4,600,000": "4,600,000 دلار",
  "Python, MySQL": "پایتون، MySQL",
  "Payrol Application": "درخواست حقوق و دستمزد",
  "company@dev.com": "company@dev.com",
  "$560,000": "560000 دلار",
  "Laravel,Metronic": "لاراول، مترونیک",
  Success: "موفقیت",
  "HR Management System": "سیستم مدیریت منابع انسانی",
  "hr@demo.com": "hr@demo.com",
  "$57,000": "57000 دلار",
  "AngularJS, C#": "AngularJS, C",
  "KTR Mobile Application": "برنامه موبایل KTR",
  "ktr@demo.com": "ktr@demo.com",
  "$45,200,000": "45,200,000 دلار",
  "ReactJS, Ruby": "ReactJS، روبی",
  "Beats Studio": "استودیو بیتز",
  "FTP: bprow@bnc.cc": "FTP: bprow@bnc.cc",
  "KTR Application": "برنامه KTR",
  "FTP:": "FTP:",
  "Telegram Mobile": "تلگرام موبایل",
  "Cisco Management": "سیسکو مدیریت",
  "Trending Items": "موارد پرطرفدار",
  "Active Customers": "مشتریان فعال",
  "Best Customers": "بهترین مشتریان",
  "Bestseller Theme": "موضوع پرفروش",
  "Amazing Templates": "قالب های شگفت انگیز",
  "Top Authors": "نویسندگان برتر",
  "Successful Fellas": "بچه های موفق",
  "Popular Authors": "نویسندگان محبوب",
  "Most Successful": "موفق ترین",
  "New Users": "کاربران جدید",
  "Awesome Users": "کاربران عالی",
  "4600 Users": "4600 کاربر",
  "354 Users": "354 کاربر",
  "7200 Users": "7200 کاربر",
  "890 Users": "890 کاربر",
  "6370 Users": "6370 کاربر",
  "Authors Earnings": "درآمد نویسندگان",
  "HTML, CSS Coding": "کد نویسی HTML، CSS",
  "$1,200,000": "1,200,000 دلار",
  "ReactJS Developer": "توسعه دهنده ReactJS",
  "$3,400,000": "3,400,000 دلار",
  "UI/UX Designer": "طراح UI/UX",
  "$4,500,000": "4,500,000 دلار",
  "Kevin Leonard": "کوین لئونارد",
  "Art Director": "کارگردان هنری",
  "$35,600,000": "35,600,000 دلار",
  "Recent Statistics": "آمارهای اخیر",
  "Recent Orders": "سفارشات اخیر",
  "More than 500 new orders": "بیش از 500 سفارش جدید",
  Year: "سال",
  "Recent Transactions": "معاملات اخیر",
  "More than 1000 new records": "بیش از 1000 رکورد جدید",
  "Recent Customers": "مشتریان اخیر",
  "More than 500 new customers": "بیش از 500 مشتری جدید",
  sales: "حراجی",
  Expenses: "مخارج",
  "Recent Users": "کاربران اخیر",
  "More than 500 new users": "بیش از 500 کاربر جدید",
  "Nick Logan": "نیک لوگان",
  "PHP, SQLite, Artisan CLI": "PHP، SQLite، Artisan CLI",
  "Outlines keep you honest. They stop you from indulging in poorly":
    "خطوط کلی شما را صادق نگه می دارد. ",
  "thought-out metaphors about driving and keep you focused on the overall":
    "استعاره های اندیشیده شده در مورد رانندگی و تمرکز شما را بر روی کلیات حفظ می کند",
  "structure of your post": "ساختار پست شما",
  "Carles Nilson": "کارلس نیلسون",
  "Yestarday at 5:06 PM": "دیروز ساعت 17:06",
  "Alice Danchik": "آلیس دانچیک",
  "1 day": "1 روز",
  Reply: "پاسخ",
  "Long before you sit dow to put digital pen to paper you need to make":
    "خیلی قبل از اینکه بنشینید و قلم دیجیتالی را روی کاغذ بیاورید که باید بسازید",
  "sure you have to sit down and write.": "حتما باید بشینی و بنویسی",
  "Harris Bold": "هریس بولد",
  "2 days": "2 روز",
  "Last week at 10:00 PM": "هفته گذشته ساعت 10:00 شب",
  "Sam Logan": "سام لوگان",
  "Mango, Java, Python": "انبه، جاوا، پایتون",
  "Mat Dillon": "مت دیلون",
  "Last month": "ماه گذشته",
  "thought-out metaphors": "استعاره های فکر شده",
  "Tasks Overview": "بررسی اجمالی وظایف",
  "Pending 10 tasks": "10 کار معلق",
  "Project Briefing": "جلسه توجیهی پروژه",
  "Project Manager": "مدیر پروژه",
  "Concept Design": "طراحی مفهومی",
  "Functional Logics": "منطق های عملکردی",
  "Lead Developer": "توسعه دهنده اصلی",
  Development: "توسعه",
  DevOps: "DevOps",
  Testing: "آزمایش کردن",
  "QA Managers": "مدیران QA",
  "Emma Smith": "اما اسمیت",
  "Sean Bean": "شان بین",
  "Brian Cox": "برایان کاکس",
  "Francis Mitcham": "فرانسیس میچام",
  "Dan Wilson": "دن ویلسون",
  Todo: "انجام دادن",
  "Create FireStone Logo": "ایجاد لوگوی FireStone",
  "Due in 2 Days": "سررسید 2 روز دیگر",
  New: "جدید",
  "Stakeholder Meeting": "نشست ذینفعان",
  "Due in 3 Days": "سررسید 3 روز دیگر",
  "Scoping & Estimations": "محدوده",
  "Due in 5 Days": "سررسید 5 روز دیگر",
  "KPI App Showcase": "نمایشگاه برنامه KPI",
  "Project Meeting": "جلسه پروژه",
  "Due in 12 Days": "سررسید 12 روز دیگر",
  "Customers Update": "به روز رسانی مشتریان",
  "Due in 1 week": "سررسید 1 هفته دیگه",
  Trends: "روندها",
  "Latest tech trends": "آخرین روندهای فناوری",
  "Mark, Rowling, Esther": "مارک، رولینگ، استر",
  "Randy, Steve, Mike": "رندی، استیو، مایک",
  "John, Pat, Jimmy": "جان، پت، جیمی",
  "Disco, Retro, Sports": "دیسکو، یکپارچهسازی با سیستمعامل، ورزش",
  "Fox Broker App": "اپلیکیشن فاکس بروکر",
  "Finance, Corporate, Apps": "امور مالی، شرکتی، برنامه ها",
  "Group lunch celebration": "جشن ناهار گروهی",
  "Navigation optimization": "بهینه سازی ناوبری",
  "Rebrand strategy planning": "برنامه ریزی استراتژی تغییر نام تجاری",
  "Product goals strategy": "استراتژی اهداف محصول",
  "Due in 7 Days": "سررسید 7 روز دیگر",
  "Latest Media": "آخرین رسانه ها",
  "Articles and publications": "مقالات و انتشارات",
  "Cup & Green": "جام",
  "Size: 87KB": "حجم: 87 کیلوبایت",
  "Yellow Background": "پس زمینه زرد",
  "Size: 1.2MB": "حجم: 1.2 مگابایت",
  "Nike & Blue": "نایک",
  "Red Boots": "چکمه های قرمز",
  "Size: 345KB": "حجم: 345 کیلوبایت",
  "Latest Products": "آخرین محصولات",
  "Gifts and more": "هدایا و بیشتر",
  "Visually stunning": "از نظر بصری خیره کننده",
  4.2: "4.2",
  "Pink Patterns": "الگوهای صورتی",
  "Feminine all around": "همه جا زنانه",
  "5.0": "5.0",
  "Abstract Art": "هنر انتزاعی",
  "The will to capture readers": "اراده برای گرفتن خوانندگان",
  5.7: "5.7",
  "Desserts platter": "بشقاب دسر",
  "Food trends & inspirations": "روندهای غذایی",
  3.7: "3.7",
  "Sales Summary": "خلاصه فروش",
  "You Balance": "شما تعادل",
  "$37,562.00": "$37,562.00",
  "100 Regions": "100 منطقه",
  "$2,5b": "2.5 میلیارد دلار",
  Revenue: "درآمد",
  "Quarter 2/3": "ربع 2/3",
  "$1,7b": "1.7 میلیارد دلار",
  Growth: "رشد",
  "80% Rate": "نرخ 80 درصد",
  "$8,8m": "8.8 میلیون دلار",
  Dispute: "اختلاف نظر",
  "3090 Refunds": "3090 بازپرداخت",
  $270m: "270 میلیون دلار",
  "Finance and accounting reports": "گزارش های مالی و حسابداری",
  "$24,500": "24500 دلار",
  "Oct 8 - Oct 26 2021": "8 اکتبر - 26 اکتبر 2021",
  "$15,300": "15300 دلار",
  "Sales Statistics": "آمار فروش",
  "Weekly Sales": "فروش هفتگی",
  "New Projects": "پروژه های جدید",
  "Item Orders": "سفارشات اقلام",
  "Bug Reports": "گزارش های اشکال",
  "Sales Progress": "پیشرفت فروش",
  "Avarage Sale": "فروش متوسط",
  Comissions: "کمیسیون ها",
  "$29,500": "29500 دلار",
  "$55,000": "55000 دلار",
  "$1,130,600": "1,130,600 دلار",
  "Sales Overview": "بررسی اجمالی فروش",
  "Recent sales statistics": "آمار فروش اخیر",
  "Average Sale": "فروش متوسط",
  Commission: "کمیسیون",
  "$233,600": "233600 دلار",
  "Annual Taxes 2019": "مالیات سالانه 2019",
  "$29,004": "29004 دلار",
  "Annual Income": "درآمد سالانه",
  "$1,480,00": "1,480,00 دلار",
  "Action Needed": "اقدام مورد نیاز",
  "Complete your profile setup": "تنظیمات پروفایل خود را کامل کنید",
  "Notes:  Current": "یادداشت ها:  فعلی",
  "sprint requires stakeholders": "اسپرینت به ذینفعان نیاز دارد",
  "to approve newly amended policies": "برای تصویب سیاست های اصلاح شده جدید",
  "Take Action": "اقدام به",
  "Latest trends": "آخرین روندها",
  "Ricky Hunt, Sandra Trepp": "ریکی هانت، ساندرا ترپ",
  "Top Sales": "فروش برتر",
  "PitStop Emails": "ایمیل های PitStop",
  "Top Engagement": "نامزدی بالا",
  "KT.com": "KT.com",
  "$2,034": "2034 دلار",
  "Author Sales": "فروش نویسنده",
  Commision: "کمیسیون",
  "Average Bid": "میانگین پیشنهاد",
  "$5.8M": "5.8 میلیون دلار",
  "All Time Sales": "فروش تمام وقت",
  "Create a headline that is informativeand will capture readers":
    "عنوانی ایجاد کنید که آموزنده باشد و خوانندگان را جذب کند",
  "Members Statistics": "آمار اعضا",
  "Over 500 members": "بیش از 500 عضو",
  "New Member": "عضو جدید",
  "Ana Simmons": "آنا سیمونز",
  "Natali Goodwin": "ناتالی گودوین",
  "Over 500 new products": "بیش از 500 محصول جدید",
  Product: "تولید - محصول",
  Price: "قیمت",
  Deposit: "سپرده",
  Agent: "عامل",
  "Sant Extreanet Solution": "محلول Sant Extreanet",
  "$2,790": "2790 دلار",
  "Bradly Beal": "برادلی بیل",
  "Telegram Development": "توسعه تلگرام",
  "$4,790": "4790 دلار",
  "Chris Thompson": "کریس تامپسون",
  "NBA Player": "بازیکن NBA",
  "Payroll Application": "درخواست حقوق و دستمزد",
  "$4,390": "4390 دلار",
  "Zoey McGee": "زویی مک گی",
  "Ruby Developer": "توسعه دهنده روبی",
  "$7,990": "7990 دلار",
  "Brandon Ingram": "براندون اینگرام",
  "$5,790": "5790 دلار",
  "Member Statistics": "آمار اعضا",
  "Over 500 new members": "بیش از 500 عضو جدید",
  Earnings: "درآمد",
  Comission: "کمیسیون",
  Rating: "رتبه بندی",
  "$8,000,000": "8,000,000 دلار",
  "$5,400": "5400 دلار",
  "Best Rated": "بهترین امتیاز",
  View: "چشم انداز",
  Edit: "ویرایش کنید",
  "$8,750,000": "8,750,000 دلار",
  "$7,400": "7400 دلار",
  "Above Avarage": "بالاتر از میانگین",
  "In Proccess": "در حال انجام است",
  "$2,500": "2500 دلار",
  "$700,000": "700000 دلار",
  "$7,760": "7760 دلار",
  Avarage: "میانگین",
  "$1,320,000": "1,320,000 دلار",
  "$6,250": "6250 دلار",
  "Over 500 orders": "بیش از 500 سفارش",
  "Order Id": "شماره سفارش",
  Country: "کشور",
  Date: "تاریخ",
  Total: "جمع",
  "56037-XDER": "56037-XDER",
  Brasil: "برزیل",
  "Code: PH": "کد: PH",
  "05/28/2020": "2020/05/28",
  "Code: Paid": "کد: پرداخت شده",
  "05822-FXSP": "05822-FXSP",
  Belarus: "بلاروس",
  "Code: BY": "کد: BY",
  "04/18/2021": "2021/04/18",
  "4472-QREX": "4472-QREX",
  Phillipines: "فیلیپین",
  "Code: BH": "کد: BH",
  "07/23/2019": "2019/07/23",
  "00347-BCLQ": "00347-BCLQ",
  Argentina: "آرژانتین",
  "Code: BR": "کد: BR",
  "12/21/2021": "2021/12/21",
  "59486-XDER": "59486-XDER",
  "Code: BT": "کد: BT",
  "tables-widget14 works!": "tables-widget14 کار می کند!",
  "Latest Arrivals": "آخرین ورودها",
  "More than 100 new products": "بیش از 100 محصول جدید",
  Angular: "زاویه ای",
  PHP: "PHP",
  HTML: "HTML",
  CSS: "CSS",
  React: "واکنش نشان دهید",
  SASS: "SASS",
  Java: "جاوا",
  Python: "پایتون",
  MySQL: "MySQL",
  Files: "فایل ها",
  "Over 100 pending files": "بیش از 100 فایل در حال انتظار",
  "5.4MB": "5.4 مگابایت",
  "2.8MB": "2.8 مگابایت",
  "1.5MB": "1.5 مگابایت",
  "500KB": "500 کیلوبایت",
  "New Members": "اعضای جدید",
  "Movie Creator": "سازنده فیلم",
  "More than 400 new products": "بیش از 400 محصول جدید",
  "React, HTML": "React، HTML",
  "More than 400 new authors": "بیش از 400 نویسنده جدید",
  "$200,500": "200500 دلار",
  "Latest Orders": "آخرین سفارشات",
  "More than 100 new orders": "بیش از 100 سفارش جدید",
  "Media Device": "دستگاه رسانه",
  "Voice and video recorder": "دستگاه ضبط صدا و تصویر",
  Ordered: "سفارش داده شده",
  "5 day ago": "5 روز پیش",
  Delivered: "تحویل داده شده",
  "Special Meal": "غذای ویژه",
  "Quona Rice": "برنج کوونا",
  "2 day ago": "2 روز پیش",
  "4 day ago": "4 روز پیش",
  "1 day ago": "1 روز پیش",
  "Strawberry Boxes": "جعبه های توت فرنگی",
  "From Spain": "از اسپانیا",
  "7 day ago": "7 روز پیش",
  "4 week ago": "4 هفته پیش",
  "2 week ago": "2 هفته پیش",
  "5 week ago": "5 هفته پیش",
  "3 month ago": "3 ماه پیش",
  "5 month ago": "5 ماه پیش",
  "6 month ago": "6 ماه پیش",
  "4 month ago": "4 ماه پیش",
  "School Music Festival": "جشنواره موسیقی مدارس",
  "by Rose Liam": "توسط رز لیام",
  "4:20PM, 03 Sep": "4:20 بعد از ظهر، 03 سپتامبر",
  "Maths Championship": "مسابقات قهرمانی ریاضی",
  "By Tom Gere": "توسط تام گیر",
  "10:05PM, 25 Oct": "25 اکتبر 20:05",
  "Who Knows Geography": "چه کسی جغرافیا می داند",
  "By Zoey Dylan": "نوشته زویی دیلن",
  "3:22PM, 07 Sep": "3:22 بعد از ظهر، 07 سپتامبر",
  "Napoleon Days": "روزهای ناپلئون",
  "By Luke Owen": "نوشته لوک اوون",
  "1:20PM, 02 Dec": "1:20 بعد از ظهر، 02 دسامبر",
  "The School Art Leads": "هنر مدرسه منجر می شود",
  "By Ellie Cole": "توسط الی کول",
  "6:20PM, 07 Sep": "18:20، 07 سپتامبر",
  "Weekly Sales Stats": "آمار فروش هفتگی",
  "890,344 Sales": "890,344 فروش",
  Bestsellers: "بهترین فروشندگان",
  "Pitstop Email Marketing": "بازاریابی ایمیلی Pitstop",
  "KT.com solution provider": "ارائه دهنده راه حل KT.com",
  "Create CRM Reports": "ایجاد گزارش های CRM",
  "Generate the latest CRM Report": "آخرین گزارش CRM را ایجاد کنید",
  "Start Now": "الان شروع کن",
  "New Products": "محصولات جدید",
  "8,600": "8600",
  "New Customers": "مشتریان جدید",
  "Create SaaSBased Reports": "ایجاد گزارش های SaaSBased",
  "Create Report": "ایجاد گزارش",
  "Create ReportsWith App": "ایجاد گزارش با برنامه",
  Properties: "خواص",
  "{{ 'PREFIX.NEW_TASKS' | translate: { PREFIX: 'There are 2 new tasks for you in “AirPlus Mobile APp”":
    "{{ 'PREFIX.NEW_TASKS' | ",
  "project:' } }}": "پروژه:' } }}",
  "{{ 'PREFIX.ADDED_AT' | translate: { PREFIX: 'Added at 4:23 PM by' }":
    "{{ 'PREFIX.ADDED_AT' | ",
  "}": "}",
  "{{ 'PREFIX.APPLICATION_DESIGN' | translate: { PREFIX:":
    "{{ 'PREFIX.APPLICATION_DESIGN' | ",
  "'Application Design' } }}": '"طراحی برنامه" } }}',
  "{{ 'PREFIX.IN_PROGRESS' | translate: { PREFIX: 'In Progress'":
    "{{ 'PREFIX.IN_PROGRESS' | ",
  "{{ 'PREFIX.CRM_SYSTEM_DEVELOPMENT' | translate: { PREFIX:":
    "{{ 'PREFIX.CRM_SYSTEM_DEVELOPMENT' | ",
  "'CRM System Development' } }}": "'توسعه سیستم CRM' } }}",
  B: "ب",
  "{{ 'PREFIX.COMPLETED' | translate: { PREFIX: 'Completed' }":
    "{{ 'PREFIX.COMPLETED' | ",
  "Invitation for crafting engaging designs that speak human":
    "دعوت نامه برای ساخت طرح های جذاب که به زبان انسان صحبت می کنند",
  workshop: "کارگاه",
  "Sent at 4:23 PM by": "ارسال شده در ساعت 16:23 توسط",
  "3 New Incoming Project Files:": "3 فایل پروژه ورودی جدید:",
  "Sent at 10:30 PM by": "ارسال در ساعت 22:30 توسط",
  "Finance KPI App Guidelines": "دستورالعمل های برنامه KPI مالی",
  "1.9mb": "1.9 مگابایت",
  "Client UAT Testing Results": "نتایج آزمایش UAT مشتری",
  "18kb": "18 کیلوبایت",
  "Finance Reports": "گزارش های مالی",
  "20mb": "20 مگابایت",
  Task: "وظیفه",
  "merged with": "ادغام با",
  "in “Ads Pro Admin Dashboard project:": "در «پروژه داشبورد مدیریت Ads Pro:",
  "Initiated at 4:23 PM by": "آغاز شده در 16:23 توسط",
  "3 new application design concepts added:":
    "3 مفهوم جدید طراحی اپلیکیشن اضافه شد:",
  "Created at 4:23 PM by": "ایجاد در 16:23 توسط",
  Explore: "کاوش کنید",
  "New case": "مورد جدید",
  "is assigned to you in Multi-platform Database Design project":
    "در پروژه طراحی پایگاه داده چند پلتفرمی به شما اختصاص داده شده است",
  "Added at 4:23 PM by": "اضافه شده در 16:23 توسط",
  "Alice Tan": "آلیس تان",
  "You have received a new order:": "شما یک سفارش جدید دریافت کرده اید:",
  "Placed at 5:05 AM by": "ساعت 5:05 توسط",
  "Login into Metronic Admin Dashboard to make sure the":
    "وارد داشبورد مدیریت مترونیک شوید تا مطمئن شوید",
  "data integrity is OK": "یکپارچگی داده ها خوب است",
  Proceed: "ادامه دهید",
  "New order": "ترتیب جدید",
  "is placed for Workshow Planning & Budget Estimation":
    "برای برنامه ریزی نمایشگاه قرار داده شده است",
  "Placed at 4:23 PM by": "ساعت 16:23 توسط",
  "Jimmy Bold": "جیمی بولد",
  Active: "فعال",
  Demos: "دموها",
  Help: "کمک",
  "Metronic Licenses": "مجوزهای مترونیک",
  "License FAQs": "سوالات متداول مجوز",
  "Regular License": "مجوز منظم",
  "For single end product used by you or one client":
    "برای محصول نهایی که توسط شما یا یک مشتری استفاده می شود",
  "Extended License": "مجوز تمدید شده",
  "For single end product with paying users.":
    "برای محصول نهایی تکی با کاربران پولی.",
  "Custom License": "مجوز سفارشی",
  "Reach us for custom license offers.":
    "برای پیشنهادات مجوز سفارشی با ما تماس بگیرید.",
  "Contact Us": "با ما تماس بگیرید",
  "Buy Now": "هم اکنون خریداری کنید",
  "Coming soon": "به زودی",
  "Learn & Get Inspired": "فرا گرفتن",
  "Support at devs.keenthemes.com": "پشتیبانی در devs.keenthemes.com",
  "Join our developers community to find answer to your question and help others.":
    "به انجمن توسعه دهندگان ما بپیوندید تا پاسخ سوال خود را بیابید و به دیگران کمک کنید.",
  FAQs: "سوالات متداول",
  "Get Support": "دریافت پشتیبانی",
  Documentation: "مستندات",
  "From guides and video tutorials, to live demos and code examples to get started.":
    "از راهنماها و آموزش های ویدئویی گرفته تا دموهای زنده و نمونه کد برای شروع.",
  "Build your layout, preview it and export the HTML for server side integration.":
    "طرح بندی خود را بسازید، پیش نمایش آن را مشاهده کنید و HTML را برای ادغام سمت سرور صادر کنید.",
  "What's New": "چه خبر",
  "Latest features and improvements added with our users feedback in mind.":
    "آخرین ویژگی ها و بهبودهایی که با در نظر گرفتن بازخورد کاربران ما اضافه شده است.",
  "Quick Links": "لینک های سریع",
  "25 pending tasks": "25 کار معلق",
  Accounting: "حسابداری",
  eCommerce: "تجارت الکترونیک",
  Administration: "مدیریت",
  Console: "کنسول",
  "Pending Tasks": "وظایف معلق",
  Customers: "مشتریان",
  "Latest cases": "آخرین موارد",
  "View All": "مشاهده همه",
  Users: "کاربران",
  Pro: "حرفه ای",
  "My Profile": "پروفایل من",
  "My Projects": "پروژه های من",
  "My Subscription": "اشتراک من",
  Referrals: "ارجاعات",
  "My Statements": "اظهارات من",
  Language: "زبان",
  "Account Settings": "تنظیمات حساب",
  "Sign Out": "خروج از سیستم",
  Light: "سبک",
  Dark: "تاریک",
  System: "سیستم",
  "Max Smith": "مکس اسمیت",
  "Upgrade to Pro": "پیشرفت",
  Developer: "توسعه دهنده",
  "SF, Bay Area": "SF، منطقه خلیج",
  "max@kt.com": "max@kt.com",
  Follow: "دنبال کردن",
  "Please wait...": "لطفا صبر کنید...",
  "Hire Me": "من را استخدام کن",
  "Success Rate": "میزان موفقیت",
  "Profile Compleation": "تکمیل نمایه",
  "Profile Details": "جزئیات نمایه",
  "Edit Profile": "ویرایش نمایه",
  "Full Name": "نام و نام خانوادگی",
  "Contact Phone": "تلفن تماس",
  "044 3276 454 935": "044 3276 454 935",
  Verified: "تایید شده است",
  "Company Site": "سایت شرکت",
  "keenthemes.com": "keenthemes.com",
  Germany: "آلمان",
  Communication: "ارتباط",
  EmailPhone: "تلفن ایمیل",
  "Allow Changes": "اجازه تغییرات",
  Yes: "آره",
  "We need your attention!": "ما به توجه شما نیاز داریم!",
  "Your payment was declined. To start using tools, please":
    "پرداخت شما رد شد. ",
  "Add Payment Method": "افزودن روش پرداخت",
  "Connected Accounts": "حساب های متصل",
  "Two-factor authentication adds an extra layer of security to your":
    "احراز هویت دو مرحله ای یک لایه امنیتی اضافی به شما اضافه می کند",
  "account. To log in, in you'll need to provide a 4 digit amazing": "حساب. ",
  code: "کد",
  "Learn More": "بیشتر بدانید",
  Google: "گوگل",
  "Plan properly your workflow": "گردش کار خود را به درستی برنامه ریزی کنید",
  Github: "Github",
  "Keep eye on on your Repositories": "مراقب مخازن خود باشید",
  Slack: "سستی",
  "Integrate Projects Discussions": "ادغام بحث های پروژه",
  Discard: "دور انداختن",
  "Save Changes": "ذخیره تغییرات",
  "Deactivate Account": "غیرفعال کردن اکانت",
  "You Are Deactivating Your Account": "شما اکانت خود را غیرفعال می کنید",
  "For extra security, this requires you to confirm your email or":
    "برای امنیت بیشتر، باید ایمیل خود را تأیید کنید یا",
  "phone number when you reset yousignr password.Learn more":
    "شماره تلفن هنگام بازنشانی رمز عبور yousignr.بیشتر بیاموزید",
  "I confirm my account deactivation":
    "من غیرفعال کردن حساب خود را تأیید می کنم",
  "Please check the box to deactivate your account":
    "لطفاً کادر را علامت بزنید تا حساب خود را غیرفعال کنید",
  "Email Preferences": "تنظیمات ایمیل",
  "Successful PaymentsReceive a notification for every successful payment.":
    "پرداخت های موفقیت آمیز برای هر پرداخت موفق یک اعلان دریافت کنید.",
  "PayoutsReceive a notification for every initiated payout.":
    "پرداخت ها برای هر پرداخت شروع شده یک اعلان دریافت کنید.",
  "Fee CollectionReceive a notification each time you collect a fee from":
    "Fee Collection هر بار که هزینه ای را از آن دریافت می کنید یک اعلان دریافت کنید",
  "Customer Payment DisputeReceive a notification if a payment is disputed by a customer and":
    "اختلاف پرداخت مشتری دریافت اخطار در صورتی که پرداخت توسط مشتری مورد مناقشه قرار گرفت و",
  "for dispute purposes.": "برای اهداف اختلاف",
  "Refund AlertsReceive a notification if a payment is stated as risk by the":
    "هشدارهای بازپرداخت در صورتی که پرداختی به عنوان ریسک توسط سازمان اعلام شود، اعلانی دریافت کنید",
  "Finance Department.": "اداره مالی.",
  "Invoice PaymentsReceive a notification if a customer sends an incorrect amount to":
    "پرداخت های فاکتور اگر مشتری مبلغ نادرستی را به آن ارسال کرد، اعلان دریافت کنید",
  "pay their invoice.": "فاکتور خود را پرداخت کنند",
  "Webhook API EndpointsReceive notifications for consistently failing webhook API":
    "Webhook API Endpoints اعلان‌هایی را برای خرابی مداوم webhook API دریافت کنید",
  "endpoints.": "نقاط پایانی",
  Phone: "تلفن",
  "Billing Updates": "به روز رسانی صورتحساب",
  "New Team Members": "اعضای جدید تیم",
  "Completed Projects": "پروژه های انجام شده",
  Newsletters: "خبرنامه ها",
  Avatar: "آواتار",
  "Select a Country...": "یک کشور را انتخاب کن...",
  Afghanistan: "افغانستان",
  "Aland Islands": "جزایر الند",
  Albania: "آلبانی",
  Algeria: "الجزایر",
  "American Samoa": "ساموآی آمریکایی",
  Andorra: "آندورا",
  Angola: "آنگولا",
  Anguilla: "آنگویلا",
  Antarctica: "جنوبگان",
  "Antigua and Barbuda": "آنتیگوا و باربودا",
  Armenia: "ارمنستان",
  Aruba: "آروبا",
  Australia: "استرالیا",
  Austria: "اتریش",
  Azerbaijan: "آذربایجان",
  Bahamas: "باهاما",
  Bahrain: "بحرین",
  Bangladesh: "بنگلادش",
  Barbados: "باربادوس",
  Belgium: "بلژیک",
  Belize: "بلیز",
  Benin: "بنین",
  Bermuda: "برمودا",
  Bhutan: "بوتان",
  "Bolivia, Plurinational State of": "بولیوی، دولت چند ملیتی",
  "Bonaire, Sint Eustatius and Saba": "بونیر، سینت اوستاتیوس و صبا",
  "Bosnia and Herzegovina": "بوسنی و هرزگوین",
  Botswana: "بوتسوانا",
  "Bouvet Island": "جزیره بووه",
  Brazil: "برزیل",
  "British Indian Ocean Territory": "قلمرو اقیانوس هند بریتانیا",
  "Brunei Darussalam": "برونئی دارالسلام",
  Bulgaria: "بلغارستان",
  "Burkina Faso": "بورکینافاسو",
  Burundi: "بوروندی",
  Cambodia: "کامبوج",
  Cameroon: "کامرون",
  Canada: "کانادا",
  "Cape Verde": "کیپ ورد",
  "Cayman Islands": "جزایر کیمن",
  "Central African Republic": "جمهوری آفریقای مرکزی",
  Chad: "چاد",
  Chile: "شیلی",
  China: "چین",
  "Christmas Island": "جزیره کریسمس",
  "Cocos (Keeling) Islands": "جزایر کوکوس (کیلینگ).",
  Colombia: "کلمبیا",
  Comoros: "کومور",
  Congo: "کنگو",
  "Congo, the Democratic Republic of the": "کنگو، جمهوری دموکراتیک",
  "Cook Islands": "جزایر کوک",
  "Costa Rica": "کاستاریکا",
  "Côte d'Ivoire": "ساحل عاج",
  Croatia: "کرواسی",
  Cuba: "کوبا",
  Curaçao: "کوراسائو",
  Cyprus: "قبرس",
  "Czech Republic": "جمهوری چک",
  Denmark: "دانمارک",
  Djibouti: "جیبوتی",
  Dominica: "دومینیکا",
  "Dominican Republic": "جمهوری دومینیکن",
  Ecuador: "اکوادور",
  Egypt: "مصر",
  "El Salvador": "السالوادور",
  "Equatorial Guinea": "گینه استوایی",
  Eritrea: "اریتره",
  Estonia: "استونی",
  Ethiopia: "اتیوپی",
  "Falkland Islands (Malvinas)": "جزایر فالکلند (مالویناس)",
  "Faroe Islands": "جزایر فارو",
  Fiji: "فیجی",
  Finland: "فنلاند",
  France: "فرانسه",
  "French Guiana": "گویان فرانسه",
  "French Polynesia": "پلینزی فرانسه",
  "French Southern Territories": "سرزمین های جنوبی فرانسه",
  Gabon: "گابن",
  Gambia: "گامبیا",
  Georgia: "گرجستان",
  Ghana: "غنا",
  Gibraltar: "جبل الطارق",
  Greece: "یونان",
  Greenland: "گرینلند",
  Grenada: "گرانادا",
  Guadeloupe: "گوادلوپ",
  Guam: "گوام",
  Guatemala: "گواتمالا",
  Guernsey: "گرنزی",
  Guinea: "گینه",
  "Guinea-Bissau": "گینه بیسائو",
  Guyana: "گویان",
  Haiti: "هائیتی",
  "Heard Island and McDonald Islands": "جزیره هرد و جزایر مک دونالد",
  "Holy See (Vatican City State)": "سریر مقدس (ایالت شهر واتیکان)",
  Honduras: "هندوراس",
  "Hong Kong": "هنگ کنگ",
  Hungary: "مجارستان",
  Iceland: "ایسلند",
  India: "هند",
  Indonesia: "اندونزی",
  "Iran, Islamic Republic of": "ایران (جمهوری اسلامی",
  Iraq: "عراق",
  Ireland: "ایرلند",
  "Isle of Man": "جزیره من",
  Israel: "اسرائيل",
  Italy: "ایتالیا",
  Jamaica: "جامائیکا",
  Japan: "ژاپن",
  Jersey: "پیراهن ورزشی",
  Jordan: "اردن",
  Kazakhstan: "قزاقستان",
  Kenya: "کنیا",
  Kiribati: "کیریباتی",
  "Korea, Democratic People's Republic of": "کره، جمهوری دموکراتیک خلق",
  Kuwait: "کویت",
  Kyrgyzstan: "قرقیزستان",
  "Lao People's Democratic Republic": "جمهوری دموکراتیک خلق لائوس",
  Latvia: "لتونی",
  Lebanon: "لبنان",
  Lesotho: "لسوتو",
  Liberia: "لیبریا",
  Libya: "لیبی",
  Liechtenstein: "لیختن اشتاین",
  Lithuania: "لیتوانی",
  Luxembourg: "لوکزامبورگ",
  Macao: "ماکائو",
  "Macedonia, the former Yugoslav Republic of": "مقدونیه، جمهوری یوگسلاوی سابق",
  Madagascar: "ماداگاسکار",
  Malawi: "مالاوی",
  Malaysia: "مالزی",
  Maldives: "مالدیو",
  Mali: "مالی",
  Malta: "مالت",
  "Marshall Islands": "جزایر مارشال",
  Martinique: "مارتینیک",
  Mauritania: "موریتانی",
  Mauritius: "موریس",
  Mayotte: "مایوت",
  Mexico: "مکزیک",
  "Micronesia, Federated States of": "میکرونزی، ایالات فدرال",
  "Moldova, Republic of": "مولداوی، جمهوری",
  Monaco: "موناکو",
  Mongolia: "مغولستان",
  Montenegro: "مونته نگرو",
  Montserrat: "مونتسرات",
  Morocco: "مراکش",
  Mozambique: "موزامبیک",
  Myanmar: "میانمار",
  Namibia: "نامیبیا",
  Nauru: "نائورو",
  Nepal: "نپال",
  Netherlands: "هلند",
  "New Caledonia": "کالدونیای جدید",
  "New Zealand": "نیوزلند",
  Nicaragua: "نیکاراگوئه",
  Niger: "نیجر",
  Nigeria: "نیجریه",
  Niue: "نیوئه",
  "Norfolk Island": "جزیره نورفولک",
  "Northern Mariana Islands": "جزایر ماریانای شمالی",
  Norway: "نروژ",
  Oman: "عمان",
  Pakistan: "پاکستان",
  Palau: "پالائو",
  "Palestinian Territory, Occupied": "سرزمین فلسطین، اشغال شده",
  Panama: "پاناما",
  "Papua New Guinea": "پاپوآ گینه نو",
  Paraguay: "پاراگوئه",
  Peru: "پرو",
  Philippines: "فیلیپین",
  Pitcairn: "پیتکرن",
  Poland: "لهستان",
  Portugal: "کشور پرتغال",
  "Puerto Rico": "پورتوریکو",
  Qatar: "قطر",
  Réunion: "تجدید دیدار",
  Romania: "رومانی",
  "Russian Federation": "فدراسیون روسیه",
  Rwanda: "رواندا",
  "Saint Barthélemy": "سنت بارتلمی",
  "Saint Helena, Ascension and Tristan da Cunha":
    "سنت هلنا، عروج و تریستان دا کونا",
  "Saint Kitts and Nevis": "سنت کیتس و نویس",
  "Saint Lucia": "سنت لوسیا",
  "Saint Martin (French part)": "سنت مارتین (بخش فرانسوی)",
  "Saint Pierre and Miquelon": "سنت پیر و میکلون",
  "Saint Vincent and the Grenadines": "سنت وینسنت و گرنادین ها",
  Samoa: "ساموآ",
  "San Marino": "سن مارینو",
  "Sao Tome and Principe": "سائوتومه و پرنسیپ",
  "Saudi Arabia": "عربستان سعودی",
  Senegal: "سنگال",
  Serbia: "صربستان",
  Seychelles: "سیشل",
  "Sierra Leone": "سیرا لئون",
  Singapore: "سنگاپور",
  "Sint Maarten (Dutch part)": "سینت مارتن (بخش هلندی)",
  Slovakia: "اسلواکی",
  Slovenia: "اسلوونی",
  "Solomon Islands": "جزایر سلیمان",
  Somalia: "سومالی",
  "South Africa": "آفریقای جنوبی",
  "South Georgia and the South Sandwich Islands":
    "جورجیا جنوبی و جزایر ساندویچ جنوبی",
  "South Korea": "کره جنوبی",
  "South Sudan": "سودان جنوبی",
  Spain: "اسپانیا",
  "Sri Lanka": "سری لانکا",
  Sudan: "سودان",
  Suriname: "سورینام",
  "Svalbard and Jan Mayen": "سوالبارد و یان ماین",
  Swaziland: "سوازیلند",
  Sweden: "سوئد",
  Switzerland: "سوئیس",
  "Syrian Arab Republic": "جمهوری عربی سوریه",
  "Taiwan, Province of China": "تایوان، استان چین",
  Tajikistan: "تاجیکستان",
  "Tanzania, United Republic of": "تانزانیا، جمهوری متحده",
  Thailand: "تایلند",
  "Timor-Leste": "تیمور شرقی",
  Togo: "رفتن",
  Tokelau: "توکلائو",
  Tonga: "تونگا",
  "Trinidad and Tobago": "ترینیداد و توباگو",
  Tunisia: "تونس",
  Turkey: "بوقلمون",
  Turkmenistan: "ترکمنستان",
  "Turks and Caicos Islands": "جزایر تورکس و کایکوس",
  Tuvalu: "تووالو",
  Uganda: "اوگاندا",
  Ukraine: "اوکراین",
  "United Arab Emirates": "امارات متحده عربی",
  "United Kingdom": "انگلستان",
  "United States": "ایالات متحده",
  Uruguay: "اروگوئه",
  Uzbekistan: "ازبکستان",
  Vanuatu: "وانواتو",
  "Venezuela, Bolivarian Republic of": "ونزوئلا، جمهوری بولیواری",
  Vietnam: "ویتنام",
  "Virgin Islands": "جزایر ویرجین",
  "Wallis and Futuna": "والیس و فوتونا",
  "Western Sahara": "صحرای غربی",
  Yemen: "یمن",
  Zambia: "زامبیا",
  Zimbabwe: "زیمبابوه",
  "Select a Language...": "انتخاب زبان...",
  "Bahasa Indonesia - Indonesian": "باهاسا اندونزی - اندونزیایی",
  "Bahasa Melayu - Malay": "باهاسا ملایو - مالایی",
  "Català - Catalan": "Català - کاتالان",
  "Čeština - Czech": "Čeština - چک",
  "Dansk - Danish": "Dansk - دانمارکی",
  "Deutsch - German": "دویچ - آلمانی",
  English: "انگلیسی",
  "English UK - British English": "انگلیسی انگلستان - انگلیسی بریتانیایی",
  "Español - Spanish": "اسپانیا - اسپانیایی",
  Filipino: "فیلیپینی",
  "Français - French": "Français - فرانسوی",
  "Gaeilge - Irish (beta)": "Gaeilge - ایرلندی (بتا)",
  "Galego - Galician (beta)": "Galego - گالیسی (بتا)",
  "Hrvatski - Croatian": "هرواتسکی - کروات",
  "Italiano - Italian": "ایتالیایی - ایتالیایی",
  "Magyar - Hungarian": "مجارستان - مجارستانی",
  "Nederlands - Dutch": "هلند - هلند",
  "Norsk - Norwegian": "نورسک - نروژی",
  "Polski - Polish": "پولسکی - لهستانی",
  "Português - Portuguese": "پرتغالی - پرتغالی",
  "Română - Romanian": "Română - رومانیایی",
  "Slovenčina - Slovak": "Slovenčina - اسلواکی",
  "Suomi - Finnish": "Suomi - فنلاندی",
  "Svenska - Swedish": "Svenska - سوئدی",
  "Tiếng Việt - Vietnamese": "Tiếng Việt - ویتنامی",
  "Türkçe - Turkish": "Türkçe - ترکی",
  "Ελληνικά - Greek": "زبان - یونانی",
  "Български език - Bulgarian": "Български език - بلغاری",
  "Русский - Russian": "Русский - روسی",
  "Српски - Serbian": "Српски - صربی",
  "Українська мова - Ukrainian": "Українська мова - اوکراینی",
  "עִבְרִית - Hebrew": "עִבְרִית - عبری",
  "اردو - Urdu (beta)": "اردو - اردو (بتا)",
  "العربية - Arabic": "العربية - عربي",
  "فارسی - Persian": "فارسی - فارسی",
  "मराठी - Marathi": "मराठी - مراتی",
  "हिन्दी - Hindi": "हिन्दी - هندی",
  "বাংলা - Bangla": "বাংলা - Bangla",
  "ગુજરાતી - Gujarati": "ગુજરાતી - گجراتی",
  "தமிழ் - Tamil": "தமிழ் - تامیل",
  "ಕನ್ನಡ - Kannada": "ಕನ್ನಡ - کانادا",
  "ภาษาไทย - Thai": "ภาษาไทย - تایلندی",
  "한국어 - Korean": "한국어 - کره ای",
  "日本語 - Japanese": "日本語 - ژاپنی",
  "简体中文 - Simplified Chinese": "简体中文 - چینی ساده شده",
  "繁體中文 - Traditional Chinese": "繁體中文 - چینی سنتی",
  "Please select a preferred language, including date, time, and":
    "لطفاً یک زبان ترجیحی، از جمله تاریخ، زمان و",
  "number formatting.": "قالب بندی اعداد",
  "Time Zone": "منطقه زمانی",
  "Select a Timezone..": "یک منطقه زمانی را انتخاب کنید..",
  "(GMT-11:00) International Date Line West":
    "(GMT-11:00) خط تاریخ بین المللی غرب",
  "(GMT-11:00) Midway Island": "(GMT-11:00) جزیره میدوی",
  "(GMT-11:00) Samoa": "(GMT-11:00) ساموآ",
  "(GMT-10:00) Hawaii": "(GMT-10:00) هاوایی",
  "(GMT-08:00) Alaska": "(GMT-08:00) آلاسکا",
  "(GMT-07:00) Pacific Time (US & Canada)":
    "(GMT-07:00) به وقت اقیانوس آرام (ایالات متحده",
  "(GMT-07:00) Tijuana": "(GMT-07:00) تیجوانا",
  "(GMT-07:00) Arizona": "(GMT-07:00) آریزونا",
  "(GMT-06:00) Mountain Time (US & Canada)":
    "(GMT-06:00) به وقت کوهستان (ایالات متحده",
  "(GMT-06:00) Chihuahua": "(GMT-06:00) چیهواهوا",
  "(GMT-06:00) Mazatlan": "(GMT-06:00) مازاتلان",
  "(GMT-06:00) Saskatchewan": "(GMT-06:00) ساسکاچوان",
  "(GMT-06:00) Central America": "(GMT-06:00) آمریکای مرکزی",
  "(GMT-05:00) Central Time (US & Canada)":
    "(GMT-05:00) به وقت مرکزی (ایالات متحده",
  "(GMT-05:00) Guadalajara": "(GMT-05:00) گوادالاخارا",
  "(GMT-05:00) Mexico City": "(GMT-05:00) مکزیکو سیتی",
  "(GMT-05:00) Monterrey": "(GMT-05:00) مونتری",
  "(GMT-05:00) Bogota": "(GMT-05:00) بوگوتا",
  "(GMT-05:00) Lima": "(GMT-05:00) لیما",
  "(GMT-05:00) Quito": "(GMT-05:00) کیتو",
  "(GMT-04:00) Eastern Time (US & Canada)":
    "(GMT-04:00) به وقت شرقی (ایالات متحده",
  "(GMT-04:00) Indiana (East)": "(GMT-04:00) ایندیانا (شرق)",
  "(GMT-04:00) Caracas": "(GMT-04:00) کاراکاس",
  "(GMT-04:00) La Paz": "(GMT-04:00) لاپاز",
  "(GMT-04:00) Georgetown": "(GMT-04:00) جورج تاون",
  "(GMT-03:00) Atlantic Time (Canada)":
    "(GMT-03:00) به وقت اقیانوس اطلس (کانادا)",
  "(GMT-03:00) Santiago": "(GMT-03:00) سانتیاگو",
  "(GMT-03:00) Brasilia": "(GMT-03:00) برازیلیا",
  "(GMT-03:00) Buenos Aires": "(GMT-03:00) بوئنوس آیرس",
  "(GMT-02:30) Newfoundland": "(GMT-02:30) نیوفاندلند",
  "(GMT-02:00) Greenland": "(GMT-02:00) گرینلند",
  "(GMT-02:00) Mid-Atlantic": "(GMT-02:00) اقیانوس اطلس میانه",
  "(GMT-01:00) Cape Verde Is.": "(GMT-01:00) کیپ ورد است.",
  "(GMT) Azores": "(GMT) آزور",
  "(GMT) Monrovia": "(GMT) مونروویا",
  "(GMT) UTC": "(GMT) UTC",
  "(GMT+01:00) Dublin": "(GMT 01:00) دوبلین",
  "(GMT+01:00) Edinburgh": "(GMT 01:00) ادینبورگ",
  "(GMT+01:00) Lisbon": "(GMT 01:00) لیسبون",
  "(GMT+01:00) London": "(GMT 01:00) لندن",
  "(GMT+01:00) Casablanca": "(GMT 01:00) کازابلانکا",
  "(GMT+01:00) West Central Africa": "(GMT 01:00) غرب آفریقای مرکزی",
  "(GMT+02:00) Belgrade": "(GMT 02:00) بلگراد",
  "(GMT+02:00) Bratislava": "(GMT 02:00) براتیسلاوا",
  "(GMT+02:00) Budapest": "(GMT 02:00) بوداپست",
  "(GMT+02:00) Ljubljana": "(GMT 02:00) لیوبلیانا",
  "(GMT+02:00) Prague": "(GMT 02:00) پراگ",
  "(GMT+02:00) Sarajevo": "(GMT 02:00) سارایوو",
  "(GMT+02:00) Skopje": "(GMT 02:00) اسکوپیه",
  "(GMT+02:00) Warsaw": "(GMT 02:00) ورشو",
  "(GMT+02:00) Zagreb": "(GMT 02:00) زاگرب",
  "(GMT+02:00) Brussels": "(GMT 02:00) بروکسل",
  "(GMT+02:00) Copenhagen": "(GMT 02:00) کپنهاگ",
  "(GMT+02:00) Madrid": "(GMT 02:00) مادرید",
  "(GMT+02:00) Paris": "(GMT 02:00) پاریس",
  "(GMT+02:00) Amsterdam": "(GMT 02:00) آمستردام",
  "(GMT+02:00) Berlin": "(GMT 02:00) برلین",
  "(GMT+02:00) Bern": "(GMT 02:00) برن",
  "(GMT+02:00) Rome": "(GMT 02:00) رم",
  "(GMT+02:00) Stockholm": "(GMT 02:00) استکهلم",
  "(GMT+02:00) Vienna": "(GMT 02:00) وین",
  "(GMT+02:00) Cairo": "(GMT 02:00) قاهره",
  "(GMT+02:00) Harare": "(GMT 02:00) هراره",
  "(GMT+02:00) Pretoria": "(GMT 02:00) پرتوریا",
  "(GMT+03:00) Bucharest": "(GMT 03:00) بخارست",
  "(GMT+03:00) Helsinki": "(GMT 03:00) هلسینکی",
  "(GMT+03:00) Kiev": "(GMT 03:00) کیف",
  "(GMT+03:00) Kyiv": "(GMT 03:00) کیف",
  "(GMT+03:00) Riga": "(GMT 03:00) ریگا",
  "(GMT+03:00) Sofia": "(GMT 03:00) صوفیه",
  "(GMT+03:00) Tallinn": "(GMT 03:00) تالین",
  "(GMT+03:00) Vilnius": "(GMT 03:00) ویلنیوس",
  "(GMT+03:00) Athens": "(GMT 03:00) آتن",
  "(GMT+03:00) Istanbul": "(GMT 03:00) استانبول",
  "(GMT+03:00) Minsk": "(GMT 03:00) مینسک",
  "(GMT+03:00) Jerusalem": "(GMT 03:00) اورشلیم",
  "(GMT+03:00) Moscow": "(GMT 03:00) مسکو",
  "(GMT+03:00) St. Petersburg": "(GMT 03:00) سن پترزبورگ",
  "(GMT+03:00) Volgograd": "(GMT 03:00) ولگوگراد",
  "(GMT+03:00) Kuwait": "(GMT 03:00) کویت",
  "(GMT+03:00) Riyadh": "(GMT 03:00) ریاض",
  "(GMT+03:00) Nairobi": "(GMT 03:00) نایروبی",
  "(GMT+03:00) Baghdad": "(GMT 03:00) بغداد",
  "(GMT+04:00) Abu Dhabi": "(GMT 04:00) ابوظبی",
  "(GMT+04:00) Muscat": "(GMT 04:00) مسقط",
  "(GMT+04:00) Baku": "(GMT 04:00) باکو",
  "(GMT+04:00) Tbilisi": "(04:00 GMT) تفلیس",
  "(GMT+04:00) Yerevan": "(GMT 04:00) ایروان",
  "(GMT+04:30) Tehran": "(GMT 04:30) تهران",
  "(GMT+04:30) Kabul": "(GMT 04:30) کابل",
  "(GMT+05:00) Ekaterinburg": "(GMT 05:00) اکاترینبورگ",
  "(GMT+05:00) Islamabad": "(GMT 05:00) اسلام آباد",
  "(GMT+05:00) Karachi": "(GMT 05:00) کراچی",
  "(GMT+05:00) Tashkent": "(GMT 05:00) تاشکند",
  "(GMT+05:30) Chennai": "(GMT 05:30) چنای",
  "(GMT+05:30) Kolkata": "(GMT 05:30) کلکته",
  "(GMT+05:30) Mumbai": "(GMT 05:30) بمبئی",
  "(GMT+05:30) New Delhi": "(GMT 05:30) دهلی نو",
  "(GMT+05:30) Sri Jayawardenepura": "(GMT 05:30) سری جایاوردنپورا",
  "(GMT+05:45) Kathmandu": "(GMT 05:45) کاتماندو",
  "(GMT+06:00) Astana": "(GMT 06:00) آستانه",
  "(GMT+06:00) Dhaka": "(GMT 06:00) داکا",
  "(GMT+06:00) Almaty": "(GMT 06:00) آلماتی",
  "(GMT+06:00) Urumqi": "(GMT 06:00) ارومقی",
  "(GMT+06:30) Rangoon": "(GMT 06:30) Rangoon",
  "(GMT+07:00) Novosibirsk": "(GMT 07:00) نووسیبیرسک",
  "(GMT+07:00) Bangkok": "(GMT 07:00) بانکوک",
  "(GMT+07:00) Hanoi": "(GMT 07:00) هانوی",
  "(GMT+07:00) Jakarta": "(GMT 07:00) جاکارتا",
  "(GMT+07:00) Krasnoyarsk": "(GMT 07:00) کراسنویارسک",
  "(GMT+08:00) Beijing": "(GMT 08:00) پکن",
  "(GMT+08:00) Chongqing": "(GMT 08:00) چونگ کینگ",
  "(GMT+08:00) Hong Kong": "(GMT 08:00) هنگ کنگ",
  "(GMT+08:00) Kuala Lumpur": "(08:00 GMT) کوالالامپور",
  "(GMT+08:00) Singapore": "(GMT 08:00) سنگاپور",
  "(GMT+08:00) Taipei": "(GMT 08:00) تایپه",
  "(GMT+08:00) Perth": "(GMT 08:00) پرث",
  "(GMT+08:00) Irkutsk": "(GMT 08:00) ایرکوتسک",
  "(GMT+08:00) Ulaan Bataar": "(08:00 GMT) اولان باتار",
  "(GMT+09:00) Seoul": "(GMT 09:00) سئول",
  "(GMT+09:00) Osaka": "(GMT 09:00) اوزاکا",
  "(GMT+09:00) Sapporo": "(GMT 09:00) ساپورو",
  "(GMT+09:00) Tokyo": "(GMT 09:00) توکیو",
  "(GMT+09:00) Yakutsk": "(GMT 09:00) یاکوتسک",
  "(GMT+09:30) Darwin": "(GMT 09:30) داروین",
  "(GMT+09:30) Adelaide": "(GMT 09:30) آدلاید",
  "(GMT+10:00) Canberra": "(GMT 10:00) کانبرا",
  "(GMT+10:00) Melbourne": "(GMT 10:00) ملبورن",
  "(GMT+10:00) Sydney": "(GMT 10:00) سیدنی",
  "(GMT+10:00) Brisbane": "(GMT 10:00) بریزبن",
  "(GMT+10:00) Hobart": "(GMT 10:00) هوبارت",
  "(GMT+10:00) Vladivostok": "(GMT 10:00) ولادی وستوک",
  "(GMT+10:00) Guam": "(GMT 10:00) گوام",
  "(GMT+10:00) Port Moresby": "(GMT 10:00) پورت مورزبی",
  "(GMT+10:00) Solomon Is.": "(GMT 10:00) Solomon Is.",
  "(GMT+11:00) Magadan": "(GMT 11:00) ماگادان",
  "(GMT+11:00) New Caledonia": "(GMT 11:00) کالدونیای جدید",
  "(GMT+12:00) Fiji": "(GMT 12:00) فیجی",
  "(GMT+12:00) Kamchatka": "(GMT 12:00) کامچاتکا",
  "(GMT+12:00) Marshall Is.": "(GMT 12:00) مارشال است.",
  "(GMT+12:00) Auckland": "(GMT 12:00) اوکلند",
  "(GMT+12:00) Wellington": "(GMT 12:00) ولینگتون",
  "(GMT+13:00) Nuku'alofa": "(GMT 13:00) Nuku'alofa",
  Currency: "واحد پول",
  "Select a currency..": "ارز را انتخاب کنید..",
  "USD - USA dollar": "USD - دلار آمریکا",
  "GBP - British pound": "GBP - پوند انگلیس",
  "AUD - Australian dollar": "AUD - دلار استرالیا",
  "JPY - Japanese yen": "JPY - ین ژاپن",
  "SEK - Swedish krona": "SEK - کرون سوئد",
  "CAD - Canadian dollar": "CAD - دلار کانادا",
  "CHF - Swiss franc": "CHF - فرانک سوئیس",
  "Allow Marketing": "اجازه بازاریابی",
  "Sign-in Method": "روش ورود به سیستم",
  "Email Address": "آدرس ایمیل",
  "support@keenthemes.com": "support@keenthemes.com",
  "Enter New Email Address": "آدرس ایمیل جدید را وارد کنید",
  "Confirm Password": "رمز عبور را تایید کنید",
  "Password is required": "رمز عبور مورد نیاز است",
  "Update Email": "ایمیل را به روز کنید",
  Cancel: "لغو کنید",
  "Change Email": "تغییر ایمیل",
  Password: "کلمه عبور",
  "Reset Password": "بازنشانی رمز عبور",
  "Current Password": "رمز عبور فعلی",
  "New Password": "رمز عبور جدید",
  "Confirm New Password": "رمز عبور جدید را تأیید کنید",
  "Password must be at least 8 character and contain symbols":
    "رمز عبور باید حداقل 8 کاراکتر و دارای نمادها باشد",
  "Update Password": "رمز عبور را به روز کنید",
  "Secure Your Account": "اکانت خود را ایمن کنید",
  "account. To log in, in addition you'll need to provide a 6 digit": "حساب. ",
  Enable: "فعال کردن",
  "My Contacts": "مخاطبین من",
  Online: "برخط",
  Declined: "نپذیرفتن",
  Accepted: "پذیرفته شده",
  "Showing 1 to 10 of 50 entries": "نمایش 1 تا 10 از 50 ورودی",
  M: "م",
  "Melody Macy": "ملودی میسی",
  "melody@altbox.com": "melody@altbox.com",
  "5 hrs": "5 ساعت",
  "20 hrs": "20 ساعت",
  "sean@dellito.com": "sean@dellito.com",
  "brian@exchange.com": "brian@exchange.com",
  "Mikaela Collins": "میکایلا کالینز",
  "mikaela@pexcom.com": "mikaela@pexcom.com",
  "f.mitcham@kpmg.com.au": "f.mitcham@kpmg.com.au",
  O: "O",
  "Olivia Wild": "اولیویا وایلد",
  "olivia@corpmail.com": "olivia@corpmail.com",
  "1 week": "1 هفته",
  N: "ن",
  "Neil Owen": "نیل اوون",
  "owen.neil@gmail.com": "owen.neil@gmail.com",
  "dam@consilting.com": "dam@consilting.com",
  "2 weeks": "2 هفته",
  E: "E",
  "Emma Bold": "اما بولد",
  "emma@intenso.com": "emma@intenso.com",
  Terms: "مقررات",
  "Fast, Efficient and Productive": "سریع، کارآمد و سازنده",
  "In this kind of post, the blogger": "در این نوع پست، وبلاگ نویس",
  "introduces a person they’ve interviewed and provides some background information about":
    "فردی را که با او مصاحبه کرده اند معرفی می کند و اطلاعاتی را در مورد زمینه ارائه می دهد",
  "the interviewee": "مصاحبه شونده",
  "and their work following this is a transcript of the interview.":
    "و کار آنها پس از این متن مصاحبه است.",
  "Forgot Password ?": "رمز عبور را فراموش کرده اید؟",
  "Enter your email to reset your password.":
    "ایمیل تان را وارد کنید تا پسوردتان ریست شود.",
  "Sorry, looks like there are some errors detected, please try again.":
    "با عرض پوزش، به نظر می رسد برخی از خطاها شناسایی شده است، لطفا دوباره امتحان کنید.",
  "Sent password reset. Please check your email":
    "بازنشانی رمز عبور ارسال شد. ",
  Submit: "ارسال",
  "Sign In.": "ورود.",
  "Your Social Campaigns": "کمپین های اجتماعی شما",
  "Sign in with Google": "با گوگل وارد شوید",
  "Sign in with Apple": "با اپل وارد شوید",
  "Or with email": "یا با ایمیل",
  "The login details are incorrect": "جزئیات ورود نادرست است",
  Continue: "ادامه هید",
  "Not a Member yet?": "آیا هنوز عضو نشده؟",
  "Sign Up": "ثبت نام",
  "logout works!": "خروج کار می کند!",
  "Or with": "یا با",
  "The registration details are incorrect": "جزئیات ثبت نام صحیح نیست",
  Fullname: "نام و نام خانوادگی",
  "'Passsword' and 'Confirm Password' didn't match.":
    "«گذرواژه» و «تأیید رمز عبور» مطابقت نداشتند.",
  "I Accept the Terms.": "من شرایط را می‌پذیرم.",
  "Already have an Account?": "از قبل یک حساب دارید؟",
  "Oops!": "اوه!",
  "We can't find that page.": "ما نمی توانیم آن صفحه را پیدا کنیم.",
  "Return Home": "بازگشت به خانه",
  "System Error": "خطای سیستم",
  "Something went wrong! Please try again later.": "مشکلی پیش آمد! ",
  "My Campaigns": "کمپین های من",
  "30 Days": "30 روز",
  "90 Days": "90 روز",
  "6 Months": "6 ماه",
  "1 Year": "1 سال",
  "Add Campaign": "اضافه کردن کمپین",
  "My Documents": "اسناد من",
  "100+ resources": "100 منبع",
  "File Manager": "مدیر فایل",
  "To Do": "انجام دادن",
  Completed: "تکمیل شد",
  "New Project": "پروژه جدید",
  "Account Type": "نوع حساب",
  "Account Info": "اطلاعات حساب",
  "Business Info": "اطلاعات کسب و کار",
  "Billing Details": "جزئیات صورتحساب",
  Back: "بازگشت",
  "Choose Account Type": "نوع حساب را انتخاب کنید",
  "If you need more info, please check out":
    "اگر به اطلاعات بیشتری نیاز دارید، لطفا بررسی کنید",
  "Help Page.": "صفحه راهنما",
  "Personal Account": "حساب شخصی",
  "If you need more info, please check it out":
    "اگر به اطلاعات بیشتری نیاز دارید، لطفا آن را بررسی کنید",
  "Corporate Account": "حساب شرکتی",
  "Create corporate account to mane users":
    "ایجاد حساب شرکتی برای مان کردن کاربران",
  "Specify Team Size": "اندازه تیم را مشخص کنید",
  "1-1": "1-1",
  "2-10": "2-10",
  "10-50": "10-50",
  "Customers will see this shortened version of your statement descriptor":
    "مشتریان این نسخه کوتاه شده شرح بیانیه شما را خواهند دید",
  "Team Account Name": "نام اکانت تیم",
  "Team Account name is required": "نام حساب تیم الزامی است",
  "Select Account Plan": "طرح حساب را انتخاب کنید",
  "Company Account": "حساب شرکت",
  "Use images to enhance your post flow":
    "از تصاویر برای بهبود جریان پست خود استفاده کنید",
  "Developer Account": "حساب توسعه دهنده",
  "Use images to your post time": "از تصاویر برای زمان ارسال خود استفاده کنید",
  "Testing Account": "حساب تست",
  "Use images to enhance time travel rivers":
    "از تصاویر برای بهبود رودخانه های سفر در زمان استفاده کنید",
  "Business Details": "جزئیات کسب و کار",
  "Business Name": "نام کسب و کار",
  "Business Name is required": "نام کسب و کار الزامی است",
  "Shortened Descriptor": "توصیفگر کوتاه شده",
  "Shortened Descriptor is required": "توصیف کننده کوتاه شده مورد نیاز است",
  "Corporation Type": "نوع شرکت",
  "S Corporation": "شرکت اس",
  "C Corporation": "شرکت سی",
  "Sole Proprietorship": "مالکیت یگانه",
  "Non-profit": "غیر انتفاعی",
  "Limited Liability": "مسئولیت محدود",
  "General Partnership": "شرکت تضامنی عمومی",
  "Business Description": "شرح کسب و کار",
  "Contact Email": "تماس با ایمیل",
  "Contact Email is required": "ایمیل تماس مورد نیاز است",
  "Wrong email format": "فرمت ایمیل اشتباه است",
  "Name On Card": "نام روی کارت",
  "Name on card is required": "نام روی کارت الزامی است",
  "Card Number": "شماره کارت",
  "Card number is required": "شماره کارت الزامی است",
  "Expiration Date": "تاریخ انقضا",
  "Expiration month is required": "ماه انقضا الزامی است",
  "Expiration year is required": "سال انقضا الزامی است",
  CVV: "CVV",
  "CVV is required": "CVV الزامی است",
  "Save Card for further billing?": "کارت برای صورت‌حساب بیشتر ذخیره شود؟",
  "If you need more info, please check budget planning":
    "اگر به اطلاعات بیشتری نیاز دارید، لطفا برنامه ریزی بودجه را بررسی کنید",
  "Save Card": "ذخیره کارت",
  "Your Are Done!": "کار شما تمام شد!",
  "If you need more info, please": "اگر به اطلاعات بیشتری نیاز دارید لطفا",
  "Writing headlines for blog posts is as much an art as it is a science and":
    "نوشتن تیتر برای پست های وبلاگ به همان اندازه که یک هنر است و علم است",
  "probably warrants its own post, but for all advise is with what works for":
    "احتمالاً پست خود را تضمین می کند، اما برای همه توصیه ها در مورد چیزی است که برای آن کار می کند",
  "your great & amazing audience.": "شما عالی هستید",
  "To start using great tools, please, please":
    "برای شروع استفاده از ابزارهای عالی، لطفا، لطفا",
  "Create Team Platform": "ایجاد پلتفرم تیم",
  "Setup Your Account Details": "جزئیات حساب خود را تنظیم کنید",
  "Setup Your Account Settings": "تنظیمات حساب خود را تنظیم کنید",
  "Your Business Related Info": "اطلاعات مربوط به کسب و کار شما",
  "Set Your Payment Methods": "روش های پرداخت خود را تنظیم کنید",
  "Woah, we are here": "وای ما اینجاییم",
  "The layout builder is to assist your set and configure your preferred":
    "سازنده layout برای کمک به مجموعه شما و پیکربندی مورد نظر شما است",
  "project layout specifications and preview it in real-time and export the":
    "مشخصات طرح پروژه و پیش نمایش آن در زمان واقعی و صادرات",
  "HTML template with its includable partials of this demo. The downloaded":
    "قالب HTML با بخش‌های قابل‌شمول آن از این نسخه آزمایشی. ",
  "version does not include the assets folder since the layout builder's":
    "نسخه شامل پوشه دارایی ها از زمان سازنده layout نیست",
  "main purpose is to help to generate the final HTML code without hassle.":
    "هدف اصلی کمک به تولید کد HTML نهایی بدون دردسر است.",
  "Layout builder changes don't affect pages with layout wrappers.":
    "تغییرات سازنده چیدمان بر صفحات دارای بسته بندی چیدمان تاثیری ندارد.",
  Sidebar: "نوار کناری",
  Header: "سرتیتر",
  Toolbar: "نوار ابزار",
  Fixed: "درست شد",
  "Fixed sidebar mode": "حالت نوار کناری ثابت",
  Minimize: "به حداقل رساندن",
  "Sidebar minimize mode": "حالت کوچک کردن نوار کناری",
  "Minimize Toggle": "Toggle را به حداقل برسانید",
  Hoverable: "قابل شناور شدن",
  "Default Minimized": "پیش فرض به حداقل رسیده است",
  "Fixed header mode": "حالت هدر ثابت",
  Content: "محتوا",
  "Header content type": "نوع محتوای سربرگ",
  Menu: "منو",
  "Page Title": "عنوان صفحه",
  "Fixed toolbar mode": "حالت نوار ابزار ثابت شد",
  Desktop: "دسکتاپ",
  Mode: "حالت",
  Mobile: "سیار",
  Layout: "چیدمان",
  "Select a toolbar layout": "طرح بندی نوار ابزار را انتخاب کنید",
  Classic: "کلاسیک",
  SaaS: "SaaS",
  Extended: "تمدید شده",
  Reports: "گزارش ها",
  Preview: "پیش نمایش",
  "IcoMoon Demo": "نسخه ی نمایشی IcoMoon",
  "Font Name: icomoon (Glyphs: 573)": "نام قلم: icomoon (گلیف: 573)",
  "Grid Size: Unknown": "اندازه شبکه: نامشخص",
};
// Define the directory where HTML files are located
const htmlDirectory = "./src/app";

// Function to process HTML files
function processHTMLFile(filePath) {
  fs.readFile(filePath, "utf8", (err, data) => {
    if (err) {
      console.error(`Error reading file ${filePath}: ${err}`);
      return;
    }

    // Iterate through each key in the JSON data
    for (const [key, translation] of Object.entries(jsonData)) {
      const pattern = new RegExp(`> ${key} <`, "gi");
      data = data.replace(pattern, `>{{'${key.charAt(0).toUpperCase() + key.slice(1)}' | translate}}<`);
    }

    // Write the modified HTML content back to the file
    fs.writeFile(filePath, data, "utf8", (err) => {
      if (err) {
        console.error(`Error writing file ${filePath}: ${err}`);
        return;
      }
      console.log(`Processed: ${filePath}`);
    });
  });
}

// Function to process files in a directory (including subdirectories)
function processFilesInDirectory(directory) {
  fs.readdir(directory, (err, files) => {
    if (err) {
      console.error(`Error reading directory ${directory}: ${err}`);
      return;
    }

    files.forEach((file) => {
      const filePath = path.join(directory, file);

      fs.stat(filePath, (err, stat) => {
        if (err) {
          console.error(`Error checking file status for ${filePath}: ${err}`);
          return;
        }

        if (stat.isDirectory()) {
          // If it's a directory, recursively process it
          processFilesInDirectory(filePath);
        } else if (file.endsWith(".html")) {
          // If it's an HTML file, process it
          processHTMLFile(filePath);
        }
      });
    });
  });
}

// Start processing HTML files in the specified directory and its subdirectories
processFilesInDirectory(htmlDirectory);
